### PR TITLE
Add "return to top" to facility page

### LINKED ISSUE #417: Add the "return to top" button on mobile facility pages
## Current state 
The return to top button is missing from the facility pages. 

## Desired state 
The return to top button is on all pages.

### PR DESCRIPTION
**Pull request by davemcorwin**
Resolves #417 

Seems to be the most reasonable place, it looked weird below the CTA...

Screen Shot 2019-10-02 at 4 56 59 PM

### CODE REVIEW

**Comment by austinhernandez** [comment]
I see it in the screenshot and it looks good. It seems as tho there is enough space and it's offset enough from the button to avoid an accidental click. However, when I click the [federalist/build link](https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/dc-417-add-return-to-top-to-facility/details/e51ee50b0707e4be10bb47834adbb9d7c173dba3e583d4802be6ed895f5dc96d?sAddr=43.0459910000000008%2C%20-76.136934999999994) I don't see it on the facilities page or any of the other pages. 

image

**Comment by allisonnorman** [comment]
Thanks @austinhernandez! It's already in production on findtreatmentbeta.18f.gov for the other pages. This was one we missed.

**Comment by davemcorwin** [comment]
@austinhernandez that looks like a desktop screenshot, this is mobile-only right now.

**Comment by austinhernandez** [comment]
I see it on mobile now, and I think it's good. Not sure where I'm supposed to approve it now. Haha

**Pull request merged**
