### PR TITLE
Add metaDescriptions and icons for preview/sharing

### LINKED ISSUE #378: Create meta descriptions and icons for sharing
We need meta descriptions for each of the pages for sharing and social media + icon(s):
- [x] Meta descriptions for each page - @amandacostello (Each content page,  /results (which is also the search page), facility details page)
- [x] Sitewide description for the homepage - @amandacostello 
- [x] Fallback description in case one doesn't exist for the page - @amandacostello 
- [x] Icon - see example below + https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image - @austinhernandez 

Example from PRA in Slack: 
Screen Shot 2019-09-26 at 1 41 44 PM

### PR DESCRIPTION
**Pull request by allisonnorman**
- [X] Add metaDescriptions for content page sub-sections

Still need to
- Add preview icon
- Add metaDescriptions for homepage/fall back and search page/results

Resolves #378

### CODE REVIEW

**Comment by hursey013** [comment]
@davemcorwin I'm worried this might conflict with the a11y changes you are making, so let's make sure we merge yours in first.

**Comment by hursey013** [comment]
@allisonnorman I'm a little worried how effective this is going to be for social sharing with it being a client side single page app. I've read that Google can spider javascript based sites so I think it will definitely be useful there, but we will need to test out how it works with social sharing once it's merged in.

**Comment by davemcorwin** [comment]
@hursey013 this is ok to merge, i can handle any conflicts.

**Comment by hursey013** [comment]
Added new issue for creating meta description on details page: https://github.com/18F/samhsa-prototype/issues/431

**Comment by allisonnorman** [comment]
I haven't been able to verify this works on social yet. Tried sharing on slack, on Facebook (only viewable by me). Is there a better way to test it?

**Pull request merged**
