### PR TITLE
Add skip link

### PR DESCRIPTION
**Pull request by hursey013**
Resolves https://github.com/18F/samhsa-prototype/issues/298

Preview:
Screen Shot 2019-10-01 at 3 13 09 PM

To test, use tab to navigate webpage. Pressing the skip link will redirect the focus of the page to `<main />`.

### CODE REVIEW

**Comment by davemcorwin** [comment]
@iamjolly May have a better sense of this, but should this be an `a` tag that points to `#main` (assuming the `id` is added) instead of a `button` tag that uses JS to set the focus?

**Comment by davemcorwin** [comment]
@Jkrzy do you have thoughts on this?

**Comment by hursey013** [comment]
@davemcorwin I can update to use `#main` instead.

**Comment by hursey013** [comment]
@davemcorwin piggybacking off your `ReturnToTop` component, this updated the skip nav to use a normal anchor link while also focusing the content.

**Comment by hursey013** [comment]
@davemcorwin holding off on merging this as well because I think it will conflict with https://github.com/18F/samhsa-prototype/pull/411

**Pull request merged**
