### PR TITLE
Prevent search engine indexing

### PR DESCRIPTION
**Pull request by hursey013**
Add robots.txt to prevent search engine indexing of beta site.

### CODE REVIEW

**Comment by allisonnorman** [comment]
@hursey013 - Just to confirm, there's no harm in pushing this now (as we don't mind if it's not indexed today), and it's easily reversible before launch? If so, we're good to merge! Thank you!

**Comment by hursey013** [comment]
@allisonnorman yep, using a robots.txt is a pretty common approach, so no harm in having it. Once we remove it (or adjust it to allow indexing) it will be scanned as per usual by search engines.

**Comment by hursey013** [comment]
@allisonnorman I'm not sure where we are tracking it, but removing the `robots.txt` should be added to our launch checklist.

**Comment by allisonnorman** [comment]
Tracking here: #344

**Pull request merged**
