### PR TITLE
Fix for distance dropdown

### PR DESCRIPTION
**Pull request by hursey013**
Fixes https://github.com/18F/samhsa-prototype/issues/163

### CODE REVIEW

**Comment by hursey013** [comment]
@allisonnorman I'd be hesitant to make the location input box much smaller, do you think it getting cut off warrants moving the dropdown down onto it's own line? Would abbreviating miles to "mi" be ok?

**Comment by allisonnorman** [comment]
I think it's fine if miles gets cut off to mi, but mi is getting cut off too. Would it be weird to put miles in the label for the drop down? "Distance (in miles)" and remove miles from the drop down?

**Comment by allisonnorman** [comment]
Or, is it possible to show miles only when the user is looking at the drop down options, but the selected option doesn't show miles? (Maybe I'm overthinking about this but throwing out options. We could always hold off to see if Nick or Austin could think about this more?)

**Comment by Jkrzy** [comment]
What about moving the units to the form label?
Screen Shot 2019-07-30 at 3 42 44 PM

**Comment by hursey013** [comment]
@allisonnorman increased size of dropdown to make sure all values are visible.

**Pull request merged**
