### PR TITLE
Route to facility page based on FRID

### PR DESCRIPTION
**Pull request by hursey013**
Fixes https://github.com/18F/samhsa-prototype/issues/146

Piggybacking off of @keithnorm's workaround here: https://github.com/18F/samhsa-prototype/pull/180 this adds the ability to navigate directly to a facility page, enabling folks to share/bookmark specific facilities.

By using a path of `/details/:frid/` along with the lat and long appended as query parameters, we are able to use the existing endpoint to search by lat/long (limiting results to only facilities with the exact lat/long), and then further filter by FRID in order to narrow the results to a single facility. This is accomplished with a single call to the endpoint.

In the future, if a new FRID specific endpoint is enabled, the `/details/:frid/` path can continued to be used (preserving existing links), and the additional query params can be dropped off.

The main caveat of this approach is that the links are dependent on the lat/long. If a facility's lat/long changes, the previous URL of the facility will no longer function.

### CODE REVIEW

**Comment by hursey013** [comment]
Unfortunately because of the way Federalist works, this isn't testable on the preview branch. It will need to be tested locally, or once merged into master.

**Comment by Jkrzy** [comment]
@hursey013, Can you expand on why this isn't testable on the federalist preview?

**Comment by hursey013** [comment]
@Jkrzy Federalist relies on the S3 404 workaround to route pages. You can only define one file to point to for the 404, and we are pointing to `/index.html`, so when you get a 404 on a preview branch, it loads in the master branch's index.html, which references `/index.html`, but since we're on a preview branch, `https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/index.html` does not exist.

**Comment by allisonnorman** [comment]
I don't have docker set up locally to see the results. Maybe we could screen share, @hursey013 or I can preview with @keithnorm.

**Comment by hursey013** [comment]
@allisonnorman added FRID to popup links on google maps

**Comment by Jkrzy** [comment]
Nice work @hursey013!

I see a few opportunities for tweaks as we move from passing data via the Results view. 

We should aim to only request facility data once. If a user is coming to the details page from results, we already have that facility data in the store and should leverage it instead of hitting the backend again.

Also, we shouldn't display the `Back to search results` link if someone has navigated directly to a facility page.

**Comment by hursey013** [comment]
Back to you @Jkrzy. Yeah I debated whether it was worth the added complexity to support the two different ways that data could be accessed, but I think I found an approach that isn't too overly complex and can be removed easily in the future.

The `Details` component will check for the existence of `facilities` data in the store (which will only be present when coming from a results page), and if it exists use that rather than firing off an additional request.

**Comment by Jkrzy** [comment]
Looks great!

There's an easy opportunity to capture some metrics on usage of direct-to-facility links/access via google events. Lets explore that in another issue.

**Pull request merged**
