### PR TITLE
Footer updates

### LINKED ISSUE #396: Revisit footer
- [X] Remove home? (Replace with required About page) - in progress
- [x] Reorganize?
- [X] Remove 4th column with SAMHSA address (that information is easily findable on the SAMHSA homepage which we link to in the first column). 
- [x] Adjust column spacing - https://gsa-tts.slack.com/archives/CGBQQ8KFD/p1569958284112600

Do we have all of the links necessary? https://digital.gov/resources/required-web-content-and-links 
- [X] Missing About Page (https://www.samhsa.gov/about-us) - in progress

### PR DESCRIPTION
**Pull request by allisonnorman**
Resolves #396

### CODE REVIEW

**Comment by allisonnorman** [comment]
@hursey013 - Made all of the changes, including removing the contact information block. You can see that even though the columns are spaced out well, visually it looks a bit off. I'd love to even out the spacing so that the shorter columns look more in line, or even to space out the left column and consolidate the two right ones. Happy to pair on it or for you to take a stab if this makes sense and then we're good to close this out.

**Comment by hursey013** [comment]
@allisonnorman did some rearranging, still not perfect, but see what you think

**Comment by allisonnorman** [comment]
@hursey013 - It looks great! I'm going to merge unless you see any reason to hold off?

**Comment by allisonnorman** [comment]
Actually just noticed github was moved. I had put that with professional resources. Let me move that back. On second look, the mission does look a little smooshed. Maybe we can talk about this for a couple minutes?

**Comment by hursey013** [comment]
@allisonnorman used some flexbox ✨to space things out a bit more

**Comment by allisonnorman** [comment]
All set and ready for approval @hursey013

**Pull request merged**
